[build]
  publish = "public"
  command = "yarn build"
[build.environment]
  YARN_VERSION = "1.3.2"
  YARN_FLAGS = "--no-ignore-optional"

[[plugins]]
package = "@uwhealth/netlify-plugin-jest"
  [plugins.inputs]
  testCommand = "jest --config ./jest/jest-config.js --collectCoverage --json --outputFile jest.results.json"
  